// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaveImageToRequiredFolder.Data;

#nullable disable

namespace SaveImageToRequiredFolder.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240524071059_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("SaveImageToRequiredFolder.Models.File", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("folderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("folderId");

                    b.ToTable("files");
                });

            modelBuilder.Entity("SaveImageToRequiredFolder.Models.Folder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("folders");
                });

            modelBuilder.Entity("SaveImageToRequiredFolder.Models.File", b =>
                {
                    b.HasOne("SaveImageToRequiredFolder.Models.Folder", "folder")
                        .WithMany()
                        .HasForeignKey("folderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("folder");
                });
#pragma warning restore 612, 618
        }
    }
}
